### ISSUE TITLE
Calendar grid disapear on manual typing

### ISSUE THREAD

**Issue by CezaryDanielNowak** [liorwohl/html5-simple-date-input-polyfill#1]
After typing anything in the date input, whole calendar grid disapears.

![http://i.imgur.com/oZ8HD43.png](http://i.imgur.com/oZ8HD43.png)

JSFIDDLE:
http://jsfiddle.net/g01bn2yp/1/

Update:
Additionally, when grid is not available, selecting anything from year/month dropdown causes Batman's issue.
_NaN-NaN-NaN_

**Comment by liorwohl** [comment]
fixed it, thanks
